# Generated by Django 3.2.4 on 2021-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_date_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.CharField(default='', max_length=100),
        ),
    ]
