# Generated by Django 3.2.4 on 2021-06-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210618_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
