# Generated by Django 3.2.4 on 2021-06-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.fullname'),
        ),
    ]
