# Generated by Django 3.2.4 on 2021-06-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shipment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.shipment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
    ]
